name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
runs:
  using: node12
  main: dist/main/index.js
inputs:
  github-token: 
    required: true
    description: Github token
  valid-commit-types: 
    required: false
    description: List of valid commit types
